//
// AGSteam: Steam API Plugin for AGS
// (C) 2011-2014 MonkeyMoto Productions, Inc.
//
// NOTICE: THIS FILE IS NOT OPEN SOURCE, AND SHOULD NEVER LEAVE THE PROPERTIES OF MONKEYMOTO PRODUCTIONS, INC.
// ("MMP") WITHOUT PRIOR EXPRESS WRITTEN PERMISSION INCLUDED AS AN ADDENDUM BELOW, ONLY BY AUTHORIZED
// PERSONNEL ACTING ON BEHALF OF MMP. IF YOU HAVE NOT BEEN SO AUTHORIZED AND HAVE OBTAINED THIS FILE, YOU ARE
// UNDER LEGAL OBLIGATION TO DELETE ALL COPIES OF IT AND ALL DERIVATIVE WORKS IMMEDIATELY. MMP AND AFFILIATED
// PARTIES SHALL NOT BE HELD LIABLE FOR ANY UNAUTHORIZED USAGE OR DISTRIBUTION OF THIS FILE, INTERNALLY OR BY
// ANY THIRD-PARTY. BY ACCESSING THIS FILE YOU ARE AGREEING TO THE TERMS AND CONDITIONS OF THIS NOTICE, AND
// ALL APPLICABLE ADDENDUMS, AND MAY BE HELD LEGALLY RESPONSIBLE FOR UNAUTHORIZED USAGE.
//
// ADDENDUM: MMP RESERVES ALL FIRST-PARTY RIGHTS TO THIS FILE AND ITS CONTENTS, INCLUDING, BUT NOT LIMITED TO
// THE RIGHT TO AUTHORIZE THIRD-PARTY USAGE OF THIS FILE, AND THE RIGHT TO REVOKE SUCH AUTHORIZATION FROM ANY
// THIRD-PARTY. AUTHORIZATION MAY BE GRANTED OR REVOKED AT ANY TIME AND FOR ANY REASON BY MMP. UPON NOTICE OF
// REVOCATION OF RIGHTS, THIRD-PARTIES MUST COMPLY IMMEDIATELY WITH THE REVISED TERMS GIVEN BY MMP. ANY
// ADDENDUMS OR CHANGES TO THIS ADDENDUM OR THE PRIOR NOTICE SHALL BE HELD NULL AND VOID BY MMP, PURSUANT TO
// THE RESTRICTIONS STATED WITHIN.
//
// ADDENDUM: IN AGREEMENT WITH WADJET EYE GAMES ("WEG"), THE FOLLOWING PRIVILEGES ARE GRANTED, BEGINNING ON
// 16 FEBRUARY 2013. AUTHORIZED PERSONNEL OF WEG ARE HEREBY AUTHORIZED BY MONKEYMOTO PRODUCTIONS, INC. TO
// ACCESS AND MODIFY THE CONTENTS OF THIS FILE, PURSUANT TO THE PRIOR RESTRICTIONS, AND THE TERMS AND
// CONDITIONS OF EXISTING NON-DISCLOSURE AGREEMENTS BETWEEN VALVE CORPORATION ("VALVE") AND MMP, AND VALVE AND
// WEG. LIMITED AUTHORIZATION IS ALSO GRANTED TO AUTHORIZED WEG PERSONNEL TO REDISTRIBUTE THIS FILE, PURSUANT
// TO THE FOLLOWING RESTRICTIONS:
//
//     THE ABOVE NOTICE AND ALL EXISTING ADDENDUMS MUST REMAIN UNCHANGED AT THE BEGINNING OF THIS C++ FILE.
//
//     WEG ACCEPTS FULL RESPONSIBILITY AND LIABILITY FOR ANY USAGE OF THIS FILE BY THIRD-PARTIES IT
//     AUTHORIZES, PURSUANT TO THEIR OWN TERMS AND RESTRICTIONS, WHICH MUST NOT PLACE ANY FURTHER LIABILITY
//     UPON MMP.
//
// ADDENDUM: ALL PARTIES ARE GRANTED NON-EXCLUSIVE LICENSE TO REDISTRIBUTE THE COMPILED FORM OF THIS C++ FILE
// FOR THE PURPOSES OF STATIC OR DYNAMIC CODE LINKING, SUCH AS IN THE FORM OF A WINDOWS DYNAMIC-LINK LIBRARY
// ("DLL") FILE. THIS ADDENDUM DOES NOT APPLY TO THE NON-COMPILED SOURCE OF THIS C++ FILE.
//
// ADDENDUM: ADDITIONAL RESTRICTIONS AND DEFINITION OF TERMS MAY BE INCLUDED IN A SEPARATE FILE NAMED
// "LICENSE" ("THE LICENSE FILE"), WITH NO TRAILING FILE EXTENSION. THE LICENSE FILE WILL BE WRITTEN IN PLAIN-
// TEXT, IN THE ENGLISH LANGUAGE, WITH A UTF-8 CHARACTER ENCODING. THE LICENSE FILE AND THIS ADDENDUM MAY BE
// AMENDED AS NECESSARY BY ANY AUTHORIZED PERSONS, WHILE UNAUTHORIZED CHANGES WILL BE NULL AND VOID.
//
#ifndef AGSteam_SteamLeaderboards_H
#define AGSteam_SteamLeaderboards_H

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#endif // WIN32_LEAN_AND_MEAN
#elif !defined(OutputDebugString) // !_WIN32
#define OutputDebugString(X) (void)X
#endif // _WIN32, !OutputDebugString

#include "steam/steam_api.h"

enum AGSteamScoresRequestType
{
  eAGSteamScoresRequestGlobal = k_ELeaderboardDataRequestGlobal,
  eAGSteamScoresRequestAroundUser = k_ELeaderboardDataRequestGlobalAroundUser,
  eAGSteamScoresRequestFriends = k_ELeaderboardDataRequestFriends
};

AGSteamScoresRequestType MapAGSteamScoresRequestToNative(int raw);
int MapAGSteamScoresRequestToAGS(AGSteamScoresRequestType);

class SteamLeaderboard
{
private:
  SteamLeaderboard_t CurrentLeaderboard;

public:
  int LeaderboardEntriesCount;
  LeaderboardEntry_t LeaderboardEntries[10];

  SteamLeaderboard();
  ~SteamLeaderboard();

  void FindLeaderboard(char const *leaderboardName);
  bool UploadScore(int score);
  bool DownloadScores(AGSteamScoresRequestType);
  char const* GetCurrentLeaderboardName();
  char const* GetLeaderName(int index);
  int GetLeaderScore(int index);

#ifndef STEAM_CALLRESULT
#define STEAM_CALLRESULT(thisclass, func, param, var) CCallResult<thisclass, param> var; void func(param *pParam, bool bIOFailure);
#define AGSTEAM_CALLRESULT
#endif // !STEAM_CALLRESULT
  STEAM_CALLRESULT(SteamLeaderboard, OnFindLeaderboard, LeaderboardFindResult_t, CallResultFindLeaderboard);
  STEAM_CALLRESULT(SteamLeaderboard, OnUploadScore, LeaderboardScoreUploaded_t, CallResultUploadScore);
  STEAM_CALLRESULT(SteamLeaderboard, OnDownloadScore, LeaderboardScoresDownloaded_t, CallResultDownloadScore);
#ifdef AGSTEAM_CALLRESULT
#undef STEAM_CALLRESULT
#undef AGSTEAM_CALLRESULT
#endif // AGSTEAM_CALLRESULT
};

char const* SteamLeaderboard_GetCurrentLeadboardName();
void SteamLeaderboard_FindLeaderboard(char const *leaderboardName);
int SteamLeaderboard_UploadScore(int score);
int SteamLeaderboard_DownloadScores(int rawType);
char const* SteamLeaderboard_GetLeaderName(int index);
int SteamLeaderboard_GetLeaderScore(int index);
int SteamLeaderboard_GetLeaderCount();

#endif // AGSteam_SteamLeaderboards_H